### ISSUE TITLE
Support for Secure Aggregation

### ISSUE THREAD

**Issue by sonnguyenasu** [apple/pfl-research#56]
Hi,
Is there any support for secure aggregation scheme on FL such as SecAgg or SecAgg+?

**Comment by grananqvist** [comment]
Hi, 
`pfl` focus on simulating the effects of PFL.
Secure aggregation techniques generally do not perturb the gradients (at least not in SecAgg and SecAgg+ that you mention), which means simulating this effect is simply the identity.
Additionally, pfl does not emulate the constraints and effects of a real-world deployed PFL system (where it would be logical to implement secure aggregation to assess the constraints it introduces).
Therefore, we do not include any implementations of common secure aggregation methods in `pfl`.

**Comment by sonnguyenasu** [comment]
Thanks for your response!
